### ISSUE TITLE
Enable Docker support and configure integration tests

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gml32#40] opened 2019-04-15 14:48 UTC
Please see:
* https://github.com/opengeospatial/cite/wiki/How-to-create-Docker-Images-of-test-suites
* https://github.com/opengeospatial/cite/wiki/How-to-run-tests-for-test-suites-with-SoapUI

**Comment by lgoltz** [comment] 2019-04-17 07:46
@dstenger Is this issue a duplicate of #36 and #31?

**Comment by dstenger** [comment] 2019-04-17 08:13
Part of this task is covered by those issues. But, the integration test configuration is still missing.

**Comment by dstenger** [comment] 2019-05-08 10:34
@keshav-nangare 
Build with `mvn clean install site -Pintegration-tests,docker` is failing.
SoapUI specific properties are missing in Maven configuration.

**Closed** 2019-05-29 12:07 UTC
Labels: enhancement
