### ISSUE TITLE
Test method validSurfaceOrientation: Ring has fewer than 3 points

### ISSUE THREAD

**Issue by sMorrone** [opengeospatial/ets-gml32#26] opened 2017-03-30 13:19 UTC
With reference to the' _Fix #20: Reduce tolerance for detecting consecutive duplicate positions_' , I am retesting - using release 1.25 - some of the files which failed with previous releases due to both ‘_Exterior boundary is not simple_’ and ‘_Ring has fewer than 3 points_’ errors. While the ‘_exterior boundary_’ issue is no more there, the ‘_Ring has fewer than 3 points_’ error is still reported. Of course no geometry in the file has only two points, so the error should depend, also in this case, on tolerance for detecting consecutive duplicate positions. The error message does not report the identifier of the failing polygon (and this issue should be solved as well), but there is only one 'small polygon' in the file, the same for which previously the "boundary is not simple" error was reported. 
Could you help ?
Thank you
Stefania
[example.3points.zip](https://github.com/opengeospatial/ets-gml32/files/881954/example.3points.zip)

**Comment by iuriemaxim** [comment] 2017-04-22 12:57
Indeed we are receiving the same error message for spikes and punctures even if there is no spike and no puncture.

According to the rule 4 from  2.1.10 Polygon section of the OGC Simple Features Specification ”A Polygon may not have cut lines, spikes or punctures”

If testing the GML or the WFS with the OGC Validator http://cite.opengeospatial.org/teamengine/about/wfs/1.0.0/site/ there are chances that some polygons to fail the Spikes and Punctures Polygon Test even if they look fine, have no topology errors and can be opened and edited with all common GIS software. Interesting is that if a spike/puncture is not passing the test, the adiacent polygon with the corresponding puncture/spike is passing the test.

A topic regarding this issue including pictures with examples of spikes and punctures that are not passing the test can be seen here https://themes.jrc.ec.europa.eu/discussion/view/90305/bug-in-the-spikes-and-punctures-test-within-ogc-and-eenvplus-validators

This is due to this bug in the algorithm that is testing the polygons for spikes and punctures, because none of these polygons have neither spikes or punctures.

The previous bug that was closed did not solved the problem, or solved the issues partly, because most of the fake spikes and punctures are not passing the test. https://github.com/opengeospatial/ets-gml32/issues/20

There are two workarounds to pass the test:
- geometry editing by adding more vertices in the area where are fake spikes/punctures, but the methodology to discover those areas is time consuming as the polygons that are falling the test need to be identified and sliced in small pieces until there is found one or more small polygons with fake spikes/punctures that are not passing the test.
- geometry of all polygons are densified by doubling or tripling the number of the vertices. For example with FME the densifier transformer can be used https://www.safe.com/transformers/densifier/ This method will increase the size of the GML sometimes to unmanageable sizes.

Most probably another algorithm need to be used by OGC. Looking at this document http://www.gdmc.nl/publications/2004/Invalid_Valid_Clean_Polygons.pdf it could be a solution to use a similar algorithm that the one used by PostGIS.

Best regards,
Iurie

**Comment by lgoltz** [comment] 2019-04-17 07:42
The failure is reproducible with the provided example. 

The test SurfaceTest.validSurfaceOrientation uses GeometryAssert.assertValidSurfaceOrientation for the validation of a surface. The surface will transformed to a right handed coordinate array cause JTS expects this:
https://github.com/opengeospatial/ets-gml32/blob/7580067273e0114dc6e8cfdcb90d7a82f995d370/src/main/java/org/opengis/cite/iso19136/data/spatial/GeometryAssert.java#L407-L408

In [GeodesyUtils.transformRingToRightHandedCS](https://github.com/opengeospatial/geomatics-geotk/blob/3e400ec87a46ab947221840a19ad5b1320598539/src/main/java/org/opengis/cite/geomatics/GeodesyUtils.java#L150) the consecutive duplicates are removed ([GeodesyUtils.removeConsecutiveDuplicates](https://github.com/opengeospatial/geomatics-geotk/blob/3e400ec87a46ab947221840a19ad5b1320598539/src/main/java/org/opengis/cite/geomatics/GeodesyUtils.java#L264)). 

## Proposal:
 * Improve the test to be executed for each surface in the test (the same applies to other tests in SurfaceTests and propably in other).
 * Improve the exception and append the gml:id of a failing surface
 * Shall the consecutive duplicates removed? 
   * If not we have to add a new method like "GeodesyUtils.transformRingToRightHandedCSKeepAllCoords"

**Comment by keshav-nangare** [comment] 2020-05-26 08:32
@dstenger @lgoltz 

I have gone through the proposed solution and did some workaround.
> Improve the test to be executed for each surface in the test (the same applies to other tests in SurfaceTests and propably in other).

I think the available tests in SurfaceTests are validating for each provided surface. Please find below reference for more details: https://github.com/opengeospatial/ets-gml32/blob/4f81dd502cba1f8d29ca9167a2916b303b1b7eb5/src/main/java/org/opengis/cite/iso19136/data/spatial/SurfaceTests.java#L149-L155

> Improve the exception and append the gml:id of a failing surface

The test assertion message includes the gml:id. We can see in below reference:
https://github.com/opengeospatial/ets-gml32/blob/4f81dd502cba1f8d29ca9167a2916b303b1b7eb5/src/main/java/org/opengis/cite/iso19136/data/spatial/GeometryAssert.java#L406-L409

> Shall the consecutive duplicates removed?
If not we have to add a new method like "GeodesyUtils.transformRingToRightHandedCSKeepAllCoords"

I went through the provided example in the first comment and found that points are too close as a result they are removed even though tolerance level is set to 1. When we try to form a ring which should have at least have 4 points but after removing we have 3 points left. 
I have added `transformRingToRightHandedCSKeepAllCoords` method in [GeodesyUtils](https://github.com/opengeospatial/geomatics-geotk/blob/3e400ec87a46ab947221840a19ad5b1320598539/src/main/java/org/opengis/cite/geomatics/GeodesyUtils.java#L31) class of [geomatic-geotk](https://github.com/opengeospatial/geomatics-geotk) dependency which will keep all coordinates and test is passing successfully.

Let me know if you want to add more to this.

**Comment by keshav-nangare** [comment] 2020-05-27 13:31
I have added a new method as per the proposed solution. The changes are successfully tested with the provided example file in the first comment.

**Comment by dstenger** [comment] 2020-09-08 16:20
I fixed by merge of #52.

**Comment by iuriemaxim** [comment] 2020-09-08 17:57
@dstenger will this solve also the wrong reported errors for spikes and punctures which actually do not exist? Do you need a gml file to test for spikes and punctures?

**Comment by dstenger** [comment] 2020-09-09 08:19
@iuriemaxim Can you please provide a test file so that we can check if this problem is solved?

**Comment by iuriemaxim** [comment] 2020-09-16 15:07
@dstenger Here they are:

http://gmlid.eu/RO/ENV/PADS/WFS?service=wfs&version=2.0.0&request=getfeature&typenames=ps:ProtectedSite&STOREDQUERY_ID=GetFeatureByINSPIREId&featureType=ps:ProtectedSite&inspireId=ps:inspireID&namespace=http://gmlid.eu/RO/ENV/PADS/PS/&localId=ROSPA0076

http://gmlid.eu/RO/ENV/PADS/WFS?service=wfs&version=2.0.0&request=GetFeature&typenames=br:Bio-geographicalRegion&featureid=alpine

Seems that they are now fine. However, I do not know if this is due to the fact that we added more vertices or because the vertices are not anymore removed during test.

The bug was observed 4 years ago. More details that could be useful are found here: https://inspire.ec.europa.eu/forum/discussion/view/90305/bug-in-the-spikes-and-punctures-test-within-ogc-and-eenvplus-validators

**Comment by iuriemaxim** [comment] 2020-09-16 20:38
@dstenger I confirm that the issue with spikes and punctures was fixed. The geometry below did not passed the test 4 years ago. Now it is passing the test.

![image](https://user-images.githubusercontent.com/20813598/93389846-70780f80-f875-11ea-9167-aeca84d62fbf.png)

**Comment by ghobona** [comment] 2020-09-23 09:22
@sMorrone @iuriemaxim 

If the problem has been fixed, shall we close this GitHub issue?

**Comment by iuriemaxim** [comment] 2020-09-23 22:39
@ghobona with the implemented solution the spikes and puncture issue does not exist anymore, so from this point it can be closed. If the example file that was provided by Silvia Morrine is not not trigerring anymore an error, than it can be closed.

**Comment by ghobona** [comment] 2020-09-25 11:04
Fixed by PR https://github.com/opengeospatial/ets-gml32/pull/59

Verified on both Beta and Production TEAM Engine instances.

**Closed** 2020-10-16 17:39 UTC
Labels: bug
