### ISSUE TITLE
2.5D points

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ets-gml32#45] opened 2019-08-12 08:01 UTC
When testing a GML file containing a 2.5D point, I get the following error: 

> org.opengis.geometry.MismatchedDimensionException: Argument ?point? has 3 dimensions, while 2 was expected.

I reproduced the error by updating org.opengis.cite.iso19136.data.spatial.VerifyPointTests, see https://github.com/heidivanparys/ets-gml32/tree/point_valid_position

The new unit test verify25DPointHasValidPosition tests https://github.com/heidivanparys/ets-gml32/blob/point_valid_position/src/test/resources/geom/Point-2.5D.xml and fails with stacktrace 

```
org.opengis.geometry.MismatchedDimensionException: Argument ‘point’ has 3 dimensions, while 2 was expected.
	at org.geotoolkit.geometry.AbstractDirectPosition.ensureDimensionMatch(AbstractDirectPosition.java:155)
	at org.geotoolkit.geometry.AbstractEnvelope.contains(AbstractEnvelope.java:578)
	at org.opengis.cite.iso19136.data.spatial.PointTests.pointHasValidPosition(PointTests.java:154)
	at org.opengis.cite.iso19136.data.spatial.VerifyPointTests.verify25DPointHasValidPosition(VerifyPointTests.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by dstenger** [comment] 2019-08-12 08:38
Thank you for reporting. We will work on a fix.

Hint for the fix: Provided unit test shall be kept and is a good basis for the branch fixing this issue.

**Comment by keshav-nangare** [comment] 2020-03-13 11:25
@dstenger 

I am able to reproduce this issue on my local machine and found that the exception is generating from third party library geotoolkit. We will discuss this issue in next meeting.

**Comment by dstenger** [comment] 2020-03-18 09:12
Issue is related to solution of #32. Currently, it is hard to fix as the problem occurs in a third-party-library.

@heidivanparys What is the priority for this issue?

**Comment by heidivanparys** [comment] 2020-03-27 08:49
Thanks for investigating, and good to know where the problem is. The priority: in one project I am participating in, it is a requirement that data are exchanged using 3D CRSs. So for that project it is blocking unfortunately.

**Comment by dstenger** [comment] 2020-03-27 18:07
@keshav-nangare Can you please check if geotoolkit can be updated and if the problem is solved in a newer version?

**Comment by keshav-nangare** [comment] 2020-04-06 12:54
@dstenger 

I went through the geotoolkit repository but unable to find the new release. Also, there is no new release in the maven central repository.

[1] http://maven.geotoolkit.org
[2]https://nexus.geomatys.com/service/rest/repository/browse/geotoolkit/org/geotoolkit/pending/geotk-xml-gml/
[3] https://mvnrepository.com/artifact/org.geotoolkit.pending/geotk-xml-gml

**Comment by dstenger** [comment] 2020-04-08 08:17
@keshav-nangare Can you please check if this test can be updated so that geotoolkit is not used anymore and support of 2.5D points is implemented in the test suite itself?

**Comment by dstenger** [comment] 2020-04-15 08:39
We will simplify following code
https://github.com/opengeospatial/ets-gml32/blob/58c335cda327693b1dbfed7ac9e3487348fb9539/src/main/java/org/opengis/cite/iso19136/data/spatial/PointTests.java#L194
by limiting the number of loops to two.
By that, a 3rd dimension will be ignored by the test.

**Comment by keshav-nangare** [comment] 2020-04-16 16:08
@dstenger 

I have updated the code as we discussed and tested the changes but still getting the same error.

I have tried to update the resource file as well but still getting the same failure. I think the failure is around the `srsName="http://www.opengis.net/def/crs/EPSG/0/7416"`


Test file:Point-2.5d.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<gml:Point
  xmlns:gml="http://www.opengis.net/gml/3.2"
  gml:id="P1"
  srsName="http://www.opengis.net/def/crs/EPSG/0/7416"
  srsDimension="3">
  <gml:pos>554494.40 6324919.14 2.00</gml:pos>
</gml:Point>
```

**Comment by dstenger** [comment] 2020-05-06 07:59
@keshav-nangare 
Can you please try to replace geotoolkit library by Apache SIS (https://sis.apache.org/) to solve this problem?
If that approach is successful, we will create a general issue to replace geotoolkit library by Apache SIS in the whole test suite.

**Comment by keshav-nangare** [comment] 2020-05-14 13:54
Following steps are tried:

- I have added the apache-sis and embedded database dependency.

- I have tried to replace geotoolkit dependent class by apache sis in PointTest class with point_valid_position test but it throws below error
 `No ‘CoordinateReferenceSystem’ object found for code “//www.opengis.net/def/crs/EPSG/0/7416” in the “EPSG” geodetic dataset`. 
- I have fixed this issue by adding the derby dependency and then ran the test but got different failure as below:

```
 java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at org.apache.sis.measure.Units.<clinit>(Units.java:1155)
	at org.apache.sis.referencing.factory.sql.EPSGDataAccess.createUnit(EPSGDataAccess.java:2458)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$21.create(AuthorityFactoryProxy.java:385)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$21.create(AuthorityFactoryProxy.java:383)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.create(ConcurrentAuthorityFactory.java:1673)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.createUnit(ConcurrentAuthorityFactory.java:1517)
	at org.apache.sis.referencing.factory.sql.EPSGDataAccess.createCoordinateSystemAxis(EPSGDataAccess.java:2358)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$20.create(AuthorityFactoryProxy.java:374)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$20.create(AuthorityFactoryProxy.java:372)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.create(ConcurrentAuthorityFactory.java:1673)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.createCoordinateSystemAxis(ConcurrentAuthorityFactory.java:1495)
	at org.apache.sis.referencing.factory.sql.EPSGDataAccess.createCoordinateSystemAxes(EPSGDataAccess.java:2294)
	at org.apache.sis.referencing.factory.sql.EPSGDataAccess.createCoordinateSystem(EPSGDataAccess.java:2149)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$12.create(AuthorityFactoryProxy.java:294)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$12.create(AuthorityFactoryProxy.java:292)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.create(ConcurrentAuthorityFactory.java:1673)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.createCoordinateSystem(ConcurrentAuthorityFactory.java:1309)
	at org.apache.sis.referencing.factory.GeodeticAuthorityFactory.createCartesianCS(GeodeticAuthorityFactory.java:989)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.createCartesianCS(ConcurrentAuthorityFactory.java:1399)
	at org.apache.sis.referencing.factory.sql.EPSGDataAccess.createCoordinateReferenceSystem(EPSGDataAccess.java:1419)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.create(AuthorityFactoryProxy.java:395)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.create(AuthorityFactoryProxy.java:393)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.create(ConcurrentAuthorityFactory.java:1673)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.createCoordinateReferenceSystem(ConcurrentAuthorityFactory.java:873)
	at org.apache.sis.referencing.factory.sql.EPSGDataAccess.createCoordinateReferenceSystem(EPSGDataAccess.java:1523)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.create(AuthorityFactoryProxy.java:395)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.create(AuthorityFactoryProxy.java:393)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.create(ConcurrentAuthorityFactory.java:1673)
	at org.apache.sis.referencing.factory.ConcurrentAuthorityFactory.createCoordinateReferenceSystem(ConcurrentAuthorityFactory.java:873)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.createFromAPI(AuthorityFactoryProxy.java:398)
	at org.apache.sis.referencing.factory.AuthorityFactoryProxy$22.createFromAPI(AuthorityFactoryProxy.java:393)
	at org.apache.sis.referencing.factory.MultiAuthoritiesFactory.create(MultiAuthoritiesFactory.java:861)
	at org.apache.sis.referencing.factory.MultiAuthoritiesFactory.createCoordinateReferenceSystem(MultiAuthoritiesFactory.java:922)
	at org.apache.sis.referencing.CRS.forCode(CRS.java:234)
	at org.opengis.cite.iso19136.data.spatial.PointTests.createDirectPosition(PointTests.java:187)
	at org.opengis.cite.iso19136.data.spatial.PointTests.pointHasValidPosition(PointTests.java:135)
	at org.opengis.cite.iso19136.data.spatial.VerifyPointTests.verify25DPointHasValidPosition(VerifyPointTests.java:34)
	.........
	.........
	.........
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for lambda expected return: interface javax.measure.quantity.Length is not convertible to interface javax.measure.Quantity
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:286)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 65 more
```

- Also I tried a different workaround by creating the sample java project and tried to get CRS for EPSG URL and it worked fine with Java 8 version.

- Today's discussion: Continue working on this issue: 1. Check if the issue can be fixed by ignoring geotoolkit dependency.

**Comment by keshav-nangare** [comment] 2020-05-19 16:58
@dstenger

The exception `call site initialization exception` has gone after removing the geomatic-geotk dependency. There are several classes used in test suite so getting errors in multiple classes. I have removed geomatic-geotk classes used in `PointTest` class for testing purpose. I have tested the changes but got the same issue as reported in the first comment.

Following are the findings  of the failure test method:

1. www.opengis.net/def/crs/EPSG/0/7416 (i.e EPSG:7416) code returns Compound CRS consists of Projected CRS(two dimensions) and Vertical CRS(third dimension).

```
CompoundCRS["ETRS89 / UTM zone 32N + DVR90 height",
  ProjectedCRS["ETRS89 / UTM zone 32N",
    BaseGeodCRS["ETRS89",
      Datum["European Terrestrial Reference System 1989",
        Ellipsoid["GRS 1980", 6378137.0, 298.257222101]],
      Unit["degree", 0.017453292519943295]],
    Conversion["UTM zone 32N",
      Method["Transverse Mercator"],
      Parameter["Latitude of natural origin", 0.0],
      Parameter["Longitude of natural origin", 9.0],
      Parameter["Scale factor at natural origin", 0.9996],
      Parameter["False easting", 500000.0],
      Parameter["False northing", 0.0]],
    CS[Cartesian, 2],
      Axis["Easting (E)", east],
      Axis["Northing (N)", north],
      Unit["metre", 1],
    Id["EPSG", 25832, "9.7"]],
  VerticalCRS["DVR90 height",
    VerticalDatum["Dansk Vertikal Reference 1990"],
    CS[vertical, 1],
      Axis["Gravity-related height (H)", up],
      Unit["metre", 1],
    Id["EPSG", 5799, "9.7"]],
  Scope["Large and medium scale topographic mapping and engineering survey."],
  Area["Denmark - onshore west of 12°E - Zealand, Jutland, Fuen and Lolland."],
  BBox[54.51, 8.00, 57.80, 12.00],
  Id["EPSG", 7416, "9.7", URI["urn:ogc:def:crs:EPSG:9.7:7416"]]]
```

2. We are creating a DirectPosition (i.e dpos) object by using above CRS and the dimensions are set as 3 as it retrieves from passed CRS as a constructor argument. 
https://github.com/apache/sis/blob/f2e8a22c7c7198d8195d7dc5a9afdc11bedf0258/core/sis-referencing/src/main/java/org/apache/sis/geometry/GeneralDirectPosition.java#L93-L96

3. We are trying to create ImmutableEnvelope using the getDomainOfValidity method of Envelope which takes CRS as a parameter from dpos and returned envelope consists of BOX and Projected CRS. The getDomainOfValidity methods never return the verticle CRS even if dpos object has the value.
https://github.com/apache/sis/blob/f2e8a22c7c7198d8195d7dc5a9afdc11bedf0258/core/sis-referencing/src/main/java/org/apache/sis/referencing/CRS.java#L803

4. That's the cause of failure envelope has 2 dimensions and DirectPosition has 3 dimensions.

`Proposed Solution:` We can create DirectPosition object using only Projected CRS because ImmutableEnvelope uses it and gets a BOX of validity from it. We also set ordinates to DirectPosition object same as the dimension size of CRS.

- I am able to run successfully with the above change and point lies inside the BOX of validity.

- I have tried the same proposed solution with geotoolkit code and able to execute it successfully but got the assertion error `java.lang.AssertionError: Point[@gml:id='P1'] is not within CRS area of use: BOX2D(265948.819050026 6417576.9372099, 677786.3628639532 7288831.70135825). expected [true] but found [false]`. I think this issue could with EPSG database version between apache sis and geotoolkit.

**Comment by ghobona** [comment] 2020-05-19 20:22
@keshav-nangare @dstenger 

I agree with the proposed solution.

**Comment by dstenger** [comment] 2020-05-20 08:26
As discussed with @keshav-nangare and @ghobona we decided to go with the proposed solution using geotoolkit. The reason being that there are several other classes that depend on geotoolkit.

**Comment by keshav-nangare** [comment] 2020-05-20 13:12
@dstenger @ghobona 

According to today's discussion, I have updated the `pointHasValidPosition` test and updated y axis and tested the changes successfully. Also, I have removed the JUnit test `point3DWith2DCRS `. 
Created the PR for same #51.

**Closed** 2020-06-26 13:13 UTC
Labels: bug, priority:high
